go get github.com/apex/log
go get github.com/blang/semver
go get github.com/go-playground/validator/v10
go get github.com/google/go-github/github
go get github.com/olekukonko/tablewriter
go get github.com/veo/vscan/nuclei_Yaml/internal/runner
go get github.com/projectdiscovery/interactsh/pkg/client
go get github.com/projectdiscovery/nuclei-updatecheck-api/client
go get github.com/projectdiscovery/nuclei/v2/pkg/catalog
go get github.com/projectdiscovery/nuclei/v2/pkg/catalog/config
go get github.com/projectdiscovery/nuclei/v2/pkg/catalog/loader
go get github.com/projectdiscovery/nuclei/v2/pkg/core
go get github.com/projectdiscovery/nuclei/v2/pkg/core/inputs/hybrid
go get github.com/projectdiscovery/nuclei/v2/pkg/model/types/severity
go get github.com/projectdiscovery/nuclei/v2/pkg/output
go get github.com/projectdiscovery/nuclei/v2/pkg/parsers
go get github.com/projectdiscovery/nuclei/v2/pkg/progress
go get github.com/projectdiscovery/nuclei/v2/pkg/projectfile
go get github.com/projectdiscovery/nuclei/v2/pkg/protocols
go get github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/automaticscan
go get github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/hosterrorscache
go get github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/interactsh
go get github.com/projectdiscovery/nuclei/v2/pkg/protocols/common/protocolinit
go get github.com/projectdiscovery/nuclei/v2/pkg/protocols/headless/engine
go get github.com/projectdiscovery/nuclei/v2/pkg/protocols/http
go get github.com/projectdiscovery/nuclei/v2/pkg/protocols/http/httpclientpool
go get github.com/projectdiscovery/nuclei/v2/pkg/reporting
go get github.com/projectdiscovery/nuclei/v2/pkg/reporting/exporters/markdown
go get github.com/projectdiscovery/nuclei/v2/pkg/reporting/exporters/sarif
go get github.com/projectdiscovery/nuclei/v2/pkg/templates
go get github.com/projectdiscovery/nuclei/v2/pkg/templates/types
go get github.com/projectdiscovery/nuclei/v2/pkg/types
go get github.com/projectdiscovery/nuclei/v2/pkg/utils
go get github.com/projectdiscovery/nuclei/v2/pkg/utils/stats
go get github.com/projectdiscovery/nuclei/v2/pkg/utils/yaml
go get github.com/tj/go-update
go get github.com/tj/go-update/progress
go get github.com/tj/go-update/stores/github
go get github.com/veo/vscan/nuclei_Yaml/internal/runner

