package hydra

func DefaultTelnetList() *AuthList {
	a := NewAuthList()
	a.Username = []string{
		"admin",
		"root",
		//"test",
		//"user",
		//"root",
		//"manager",
		//"webadmin",
	}
	a.Password = []string{
		"1",
		"123456",
		//"zaq1@WSX",
		//"%user%",
		//"%user%123",
		//"%user%1234",
		//"%user%123456",
		//"%user%12345",
		//"%user%@123",
		//"%user%@123456",
		//"%user%@12345",
		//"%user%#123",
		//"%user%#123456",
		//"%user%#12345",
		//"%user%_123",
		//"%user%_123456",
		//"%user%_12345",
		//"%user%123!@#",
		//"%user%!@#$",
		//"%user%!@#",
		//"%user%~!@",
		//"%user%!@#123",
		//"%user%2022",
		//"%user%2021",
		//"%user%2020",
		//"%user%2019",
		//"%user%2018",
		//"%user%2017",
		//"%user%2016",
		//"%user%2015",
		//"%user%@2017",
		//"%user%@2016",
		//"%user%@2015",
		//"qweasdzxc",
		//"Passw0rd",
		//"admin123!@#",
		//"admin",
		//"admin123",
		//"admin@123",
		//"admin#123",
		//"password",
		//"12345",
		//"1234",
		//"123",
		//"qwerty",
		//"1q2w3e4r",
		//"1qaz2wsx",
		//"qazwsx",
		//"123qwe",
		//"123qaz",
		//"1234567",
		//"123456qwerty",
		//"password123",
		//"12345678",
		//"1q2w3e",
		//"abc123",
		//"test123",
		//"123456789",
		//"q1w2e3r4",
		//"0000",
		//"root",
		//"test",
		//"okmnji",
		//"postgres",
		//"user",
	}
	a.Special = []Auth{
		NewSpecialAuth("admin", "admin"),
		NewSpecialAuth("oracle", "oracle"),
		NewSpecialAuth("postgres", "postgres"),
		NewSpecialAuth("db2admin", "db2admin"),
		NewSpecialAuth("defaultUsername", "defaultPassword"),
		NewSpecialAuth("admin", "Admin@huawei"),
		NewSpecialAuth("admin", "admin@huawei.com"),
		NewSpecialAuth("admin", "admin"),
		NewSpecialAuth("admin", "Admin@123"),
		NewSpecialAuth("admin", "Changeme_123"),
		NewSpecialAuth("admin", "Admin123"),
		NewSpecialAuth("admin", "Changeme123"),
		NewSpecialAuth("admin", "Admin@storage"),
		NewSpecialAuth("admin", "eSight@123"),
		NewSpecialAuth("admin", "Cis#BigData123"),
		NewSpecialAuth("admin", "Huawei@123"),
		NewSpecialAuth("LogAdmin", "Changeme123"),
		NewSpecialAuth("SystemAdmin", "Changeme123"),
		NewSpecialAuth("OperateAdmin", "Changeme123"),
		NewSpecialAuth("administrator", "Changeme123"),
		NewSpecialAuth("Administrator", "Admin@9000"),
		NewSpecialAuth("Administrator", "Changeme@321"),
		NewSpecialAuth("api-admin", "admin@123"),
		NewSpecialAuth("root", "admin123"),
		NewSpecialAuth("root", "mduadmin"),
		NewSpecialAuth("root", "Changeme_123"),
		NewSpecialAuth("root", "admin"),
		NewSpecialAuth("root", "adminHW"),
		NewSpecialAuth("root", "password"),
		NewSpecialAuth("root", "Huawei12#$"),
		NewSpecialAuth("root", "Changeme@321"),
		NewSpecialAuth("root", "Changeme123"),
		NewSpecialAuth("sa", "Changeme123"),
	}
	return a
}
